name: respire
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  numberpicker: ^2.1.2
  dropdown_button2: ^2.3.9
  custom_sliding_segmented_control: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_biale_tlo.png
    - assets/logo_poziom.png
    - assets/kropki_1.png
    - assets/kropki_2.png

  fonts:
    - family: Mouldy
      fonts:
        - asset: fonts/MouldyCheese.ttf
    - family: Oblata
      fonts:
        - asset: fonts/OblataDisplay.otf
    - family: Yeasty
      fonts:
        - asset: fonts/YeastyFlavors.ttf
    - family: Guavine
      fonts:
        - asset: fonts/GuavineDemo.otf
    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel-Bold.otf
    - family: Glacial
      fonts:
        - asset: fonts/GlacialIndifference-Regular.otf